### ISSUE TITLE
Remove Unnecessary Libgcrypt Version Check

### ISSUE THREAD

**Issue by IbraheemYSaleh** [nasa/CryptoLib#138]
While using the libgcrypt interface, you get a version check error message if not using V1.9.4.

This version check & error message are unnecessary and should be removed:
https://github.com/nasa/CryptoLib/blob/dev/src/src_cryptography/src_libgcrypt/cryptography_interface_libgcrypt.template.c#L549

**Comment by dccutrig** [comment]
Not sure that this needs done - although it should only check if using libgcrypt. I believe there was a specific reason we landed on that as a minimum version, although I don't recall what it was or that we communicated it to Ibraheem. Perhaps @rjbrown2 recalls

**Comment by jlucas9** [comment]
https://github.com/nasa/CryptoLib/blob/dev/src/crypto/libgcrypt/cryptography_interface_libgcrypt.template.c#LL108C1-L109C1
^ Updated link

**Comment by jlucas9** [comment]
Leaving in for now to ensure built version of Gcrypt matches running version of libgcrypt. Can reconsider again if another issue arises.
