### ISSUE TITLE
Unit Test Review

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#149]
Should testing be performed in cycles?
* Setup a specific configuration (managed parameters and SA parameters) then run all the tests in that configuration? Rinse and repeat?

Can the PICs from the SDLS and SDLS-EP standards drive our tests?

Ideally the same unit tests can be run no matter the "module" or build flags used!

**Comment by rjbrown2** [comment]
Unit tests could use another once over.  But closing this for now.
