### ISSUE TITLE
KMC Support of Null IV

### ISSUE THREAD

**Issue by dccutrig** [nasa/CryptoLib#157]
When KMC is used and an IV is null, KMC will generate its own IV internally and return it to CryptoLib to be placed in the frame. 

Add Code to handle SN as the precedence counter if iv is unmanaged?

**Comment by dccutrig** [comment]
@rjbrown2 making a note here to walk-through Check_Anti_Replay flow and not automatically return for Null pointers -> they could possible be Null because there is no ARSN? Just a thought, needs a deeper review through the various levels

**Comment by jlucas9** [comment]
Merged into `dev` in commit 9c1255a9ead1769421f8f42a55ee8dec9bf376f3
