### ISSUE TITLE
AOS Support

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#169]

**Comment by dccutrig** [comment]
Note: Potential API modification to Crypto_Config_Add_Gvcid_Managed_Parameter to allow setting an AOS managed parameter: Has_Fhec (frame header error control).

Mentioning here for awareness.
[169-aos-support 94dd85e]

**Comment by dccutrig** [comment]
In addition to above, adding logic for AOS Insert Zone presence and length

**Comment by dccutrig** [comment]
Tracking for an issue that has to do with CryptoLib. CrpytoLib or KMC seem to be replacing a NULL IV with a 0, which is inappropriate behavior.

**Comment by jlucas9** [comment]
Merged to `dev`
