### ISSUE TITLE
Default SA Update

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#171]
What should be the default SA configuration for use?

0, TC, clear
1, TC, authenticated encryption
2, TC, encryption only
3,TC, authentication only
…
8, TM, clear
9, TM, authenticated encryption
10, TM, encryption only
11, TM, authentication only
…
16, AOS, clear
17, AOS, authenticated encryption
18, AOS, encryption only
19, AOS, authentication only

**Comment by rjbrown2** [comment]
Default SAs updated.
