### ISSUE TITLE
TC_Apply AEAD Enc Review

### ISSUE THREAD

**Issue by dccutrig** [nasa/CryptoLib#191]
Identified a possible issue in TC_Apply if using an AEAD algorithm for encryption only. Need to assess further, deals with AAD not being generated for encryption only, but being freed in error cases.

**Comment by Donnie-Ice** [comment]
This is no longer an issue. `uint8_t *aad` is initialized to NULL in all TC_Apply calls and is always freed. The code may have worked differently when this issue was created.
