### ISSUE TITLE
AES-GCM-SIV

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#197]
Add support for AES_GCM_SIV algorithm

**Comment by Donnie-Ice** [comment]
WolfSSL only has support for AES_SIV, not AES_GCM_SIV. [(ref)](https://crypto.stackexchange.com/questions/87895/aes-gcm-siv-implementation)

**Comment by Donnie-Ice** [comment]
[RFC 8452 - AES_GCM_SIV](https://datatracker.ietf.org/doc/rfc8452/?include_text=1)
