### ISSUE TITLE
Re-evaluate CodeCov App being used in CI

### ISSUE THREAD

**Issue by dccutrig** [nasa/CryptoLib#215]
Update CodeCov App being used in CI... either need fixed or a better solution. 

Currently not getting full coverage of all of the code because of the way our build has changed - looks like codecov isn't touching every file.

**Comment by Donnie-Ice** [comment]
CodeCov now allows merging reports: [Link](https://docs.codecov.com/docs/merging-reports)

It seems that this should solve coverage percentages.

**Comment by jlucas9** [comment]
Merged into `dev`
