### ISSUE TITLE
Revisit Crypto_TC_Accio_Buffer

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#233]
Per https://github.com/nasa/CryptoLib/pull/232#discussion_r1539437911

**Comment by rjbrown2** [comment]
This is a malloc this is only for the ground-side implementation.  There's possibility that this could be pulled out into build flags.  But it is necessary for KMC to utilize the library on their side.  We should probably leave this as is, unless we want to do some larger refactoring, and cmake logic.
