### ISSUE TITLE
CMake Custom Module Paths

### ISSUE THREAD

**Issue by williamposey** [nasa/CryptoLib#240]
Path variables for the custom module source files should be added to the cryptolib CMake files. If the variable is not set, then a default path can be used. For example, rather than using `aux_source_directory(../../sa/custom SA_CUSTOM_FILES)` in [CMakeLists.txt](https://github.com/nasa/CryptoLib/blob/main/src/CMakeLists.txt#L96) it would contain `aux_source_directory(SA_CUSTOM_PATH SA_CUSTOM_FILES)`. Somewhere else, possibly in the top level [CMakeLists.txt](https://github.com/nasa/CryptoLib/blob/main/CMakeLists.txt) file, a check could be included to set the path to a default value if not already set: 
```
if(NOT DEFINED SA_CUSTOM_PATH)
  set(SA_CUSTOM_PATH ../../sa/custom)
endif()
```

This should be done for all custom modules, as it would allow for the open source to be mirrored without any modification more easily

**Comment by jlucas9** [comment]
Merged into `dev`
