### ISSUE TITLE
Klocwork SA

### ISSUE THREAD

**Issue by rjbrown2** [nasa/CryptoLib#27]
Setup environment and test build of code with CentOS, as well as run SA over codebase.

**Comment by rjbrown2** [comment]
This is complete for the first formal release.  It has not yet been fully reviewed.  But the static analysis results are complete.

**Comment by szemerick** [comment]
review of SA results is complete.  Reviewed all critical issues.  Ignored anything related to test code, which was mostly checking for NULL pointers after mallocs.  Several small issues fixed, and 1 bug identified: a missing _return_ statement would have caused a NULL pointer dereference in an error/edge case.

**Comment by jlucas9** [comment]
Merged into `collab_main`!
