### ISSUE TITLE
Packaging Problems

### ISSUE THREAD

**Issue by Niautanor** [nasa/CryptoLib#271]
I would like to package cryptolib for our yocto build and ran into two problems that I wanted to get maintainer feedback on before I propose a merge request:

1. It is currently not possible to install the library into any location other than /usr/local/ (which gets enforced when SYSTEM_INSTALL is ON) or locally into an install/ subdirectory in the repository (which gets enforced when SYSTEM_INSTALL is OFF (and cryptolib is not being built as a cFE library)).
   - I am honestly not entirely sure why CMAKE_PREFIX_PATH gets forced to /usr/local in the SYSTEM_INSTALL case since [/usr/local is the default](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html). Could the explicit setting of CMAKE_PREFIX_PATH in this case maybe be omitted?
2. The library file which gets installed is called libcrypto.so. Unfortunately, openssl also calls itself libcrypto.so which would cause conflicts
   - What would be the opinions about changing the installed name of the library to something like libcryptolib.so?

**Comment by rjbrown2** [comment]
I think this is a great idea.  There's really no reason to force the SYSTEM_INSTALL location.  Also, the shared object name can be changed as well, as this is also a good suggestion and catch.  We look forward to your pull request, and will happily merge this change in.

Thanks!!
