### ISSUE TITLE
Cryptography_IF Wrapper Update

### ISSUE THREAD

**Issue by rjbrown2** [nasa/CryptoLib#284]
Should the crypto module section match the other modules, and be encased in a `if (cryptography_if == NULL)` statement?

_Originally posted by @williamposey in https://github.com/nasa/CryptoLib/pull/276#discussion_r1722357672_

**Comment by Donnie-Ice** [comment]
Not sure if `cryptography_init()` and `cryptography_config()` should go inside the null check. Can you take a look @rjbrown2 ?
