### ISSUE TITLE
Setup code formatter

### ISSUE THREAD

**Issue by jlucas9** [nasa/CryptoLib#299]
Can just leverage other clang format setups, but ought to have it in the project and if possible have commits get formatted.

**Comment by rjbrown2** [comment]
https://github.com/marketplace/actions/c-c-linter

Thoughts on this?

**Comment by Donnie-Ice** [comment]
Default format code is checked against: https://llvm.org/docs/CodingStandards.html

**Comment by rjbrown2** [comment]
This is set up.  We should go over which format standard we want to use, and a path forward for how we want to address each of the issues that are found.

Leaving open for now.
