### ISSUE TITLE
Crypto.C - Cleanup

### ISSUE THREAD

**Issue by rjbrown2** [nasa/CryptoLib#316]
- [x] Check IV-len against maximum IV- Length (Will need to be defined)
- [x] Check Gvcid Counter against bounds
- [x] Check for Null Pointers
- [x] Check for Size > 0
- [x] Clean up Commented COde
- [ ] Finish or Remove TODOS
- [x] (~Line 147) - Add return code, and fix to single return statement
- [x] (235 - Unused Code)  Remove?
- [x] Remove //Testing Code Comment - and specify what these are
- [x] Remove Magic Numbers
- [x] Add more comments

**Comment by Donnie-Ice** [comment]
Not sure about cases of `Check for Size > 0`. For-loops do that automatically. Marking as complete for now.
