### ISSUE TITLE
Define Specific SDLS-EP SAs

### ISSUE THREAD

**Issue by Donnie-Ice** [nasa/CryptoLib#354]
Currently there is no mechanism to restrict Extended Procedure calls to the 'min' or 'max' security associations.
Extended procedures should be restricted to these SAs.
Additionally, it needs to be ensured that the SPI associated with SAs cannot be modified.
Add logic to restrict to these SAs, and to validate that the SPI is for the appropriate SA, and the SPI hasn't been modified.

**Comment by Donnie-Ice** [comment]
sa[14] dupe

**Comment by rjbrown2** [comment]
#362
