### ISSUE TITLE
OTAR Decryption doesn't check status of decryption

### ISSUE THREAD

**Issue by Donnie-Ice** [nasa/CryptoLib#355]
More context:

OTAR allows multiple encrypted keys and their key ids to be updated at once. 

More or less, this is in the format of [encrypted key id] [encrypted key] [repeats n times]

On the receiving end for otar, the keys are decrypted and stored in memory. It is unclear exactly how the OTAR decryption for a given key would fail, but the status should be returned regardless.

**Comment by dccutrig** [comment]
@jlucas9 @rjbrown2 @Donnie-Ice Should we be able to re-key master keys with OTAR? Seems... desirable in a worst case scenario? Current implementation prohibits this. Worth discussion.

**Comment by Otan2** [comment]
> It is unclear exactly how the OTAR decryption for a given key would fail, but the status should be returned regardless.

Cryptolib is using `CRYPTO_CIPHER_AES256_GCM` as per the standard to perform authenticated encryption of the OTAR procedure (and not encryption only). Therefore, the crypto function status returns an error when the computed mac and provided mac are not the same
