### ISSUE TITLE
sa_create needs bounds checking

### ISSUE THREAD

**Issue by CutrightD** [nasa/CryptoLib#357]
SA_Create has the potential to wreck CryptoLib by not enforcing checks on lengths of the SA.

Example from SA_Create:

sa[spi].shivf_len  = ((uint8_t)sdls_frame.pdu.data[2] & 0x3F);

sa[spi].shivf_len could be in this way set to something larger than the bounds of sa[spi].iv[IV_LEN]

Note: We know that we're in the process of maturing the SDLS-EP functions and that work is on-going, but things like this will need extra scrutiny as we come back up to speed on the EPs.

**Comment by dccutrig** [comment]
Additional comment: Do we have the notion, or does the standard define, which key ranges are master keys? Currently we error if we try to OTAR a master key, if this desired?
