### ISSUE TITLE
Examine EP Modification Calls

### ISSUE THREAD

**Issue by dccutrig** [nasa/CryptoLib#367]
SDLS EP directives should never modify the SA they're being transmitted across.

Examine this deeper in code and ensure this is the case.

This could cause loss of mission (e.g. modifying SA 0 while using SA 0) and not being able to modify it anymore.

**Comment by Donnie-Ice** [comment]
Confirmed you can modify SA 0 while using SA 0

**Comment by Donnie-Ice** [comment]
May require modifying sa_interface. Pass ingest to sa_stop (other functions may require more)
