### ISSUE TITLE
Add Support for the Libgcrypt-based Encryption Interface to support an External PKCS12 Keyring

### ISSUE THREAD

**Issue by IbraheemYSaleh** [nasa/CryptoLib#58]
Currently, CryptoLib with libgcrypt only supports the internal, in-memory keyring. 

Some missions/projects will want to use libgcrypt encryption functions (as an alternative to the KMC Crypto Service) with their own pkcs12 keystore. We should support libgcrypt to be configured with an external pksc12 keystore.

**Comment by jlucas9** [comment]
Will reopen should a PKCS12 keyring be required in the future. Initial review of open-source C libraries to support this was unfruitful.
